<?php

namespace Tests\Unit;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class AnswerApiUnitTest extends TestCase
{
    protected $response;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->response = $this->actingAs($this->user, 'api');
    }


    /**
     * @param int $quantity
     * @return mixed
     */
    public function createAnswer(int $quantity = 1)
    {
        return factory(\App\Models\Answer::class, $quantity)
            ->create([
                'question_id' => factory(\App\Models\Question::class)->create()->id
            ]);
    }

    public function createQuetion()
    {
        return factory(\App\Models\Question::class)->create();
    }

    public function testCreate(): void
    {
        $question =  $this->createQuetion();

        $data = [
            'question_id' => $question->id,
            'description' => $this->faker->realText(15),
            'is_valid' => true];

        $this->response
            ->json('POST', '/api/answers', $data)
            ->assertStatus(201)
            ->assertJson([
                'created' => true,
                'id' => true
            ]);
    }

    public function testCreateErrorValidation(): void
    {
        $data = [
//            'question_id' => $this->createQuetion()->id,
            'is_valid' => true];

        $this->response
            ->json('POST', '/api/answers', $data)
            ->assertStatus(422)
            ->assertJsonStructure(['message', 'errors'])
            ->assertJson([
                'errors' => [
                    'description' => ['The description field is required.'],
                    'question_id' => ['The question id field is required.']
                ]
            ]);
    }

    public function testCreateErrorQuestionIdExists(): void
    {
        $data = [
            'description' => $this->faker->realText(15),
            'question_id' => 3,
            'is_valid' => true];

        $this->response
            ->json('POST', '/api/answers', $data)
            ->assertStatus(422)
            ->assertJsonStructure(['message', 'errors'])
            ->assertJson([
                'errors' => [
                    'question_id' => ['The selected question id is invalid.'],
                ]
            ]);
    }

    public function testIndex(): void
    {
        $this->createAnswer(10);

        $this->response
            ->json('GET', '/api/answers')
            ->assertStatus(200)
            ->assertJsonStructure([
                'data' =>[['id', 'description', 'question_id', 'is_valid']],
            ]);
    }

    public function testShow(): void
    {
        $this->createAnswer(1);

        $this->response
            ->json('GET', '/api/answers/1')
            ->assertStatus(200)
            ->assertJsonStructure(['id', 'description', 'question_id', 'is_valid']);
    }

    public function testShowNotElement(): void
    {
        $this->response
            ->json('GET', '/api/answers/1')
            ->assertStatus(404);
    }

    public function testUpdate(): void
    {
        $answer = $this->createAnswer(1)[0];

        $data = [
            'description' => $this->faker->realText(15),
            'is_valid' => true];

        $this->response
            ->json('PUT', '/api/answers/' . $answer->id, $data)
            ->assertStatus(200)
            ->assertJsonStructure(['id', 'description', 'question_id', 'is_valid']);
    }

    public function testUpdateNotElement(): void
    {
        $data = [
            'description' => $this->faker->realText(15),
            'is_valid' => true];

        $this->response
            ->json('PUT', '/api/answers/1', $data)
            ->assertStatus(404);
    }


    public function testUpdateErrorValidation(): void
    {
        $answer = $this->createAnswer(1)[0];

        $data = [
            'is_valid' => true];

        $this->response
            ->json('PUT', '/api/answers/'.$answer->id, $data)
            ->assertStatus(422)
            ->assertJsonStructure(['message', 'errors'])
            ->assertJson([
                'errors' => [
                    'description' => ['The description field is required.']
                ]
            ]);
    }
}
