<?php

namespace Tests\Unit;

use Tests\TestCase;

class QuizApiUnitTest extends TestCase
{

    protected $response;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->response = $this->actingAs($this->user, 'api');
    }

    public function testCreate()
    {
        $data = [
            'title' => $this->faker->title,
            'public' => rand(0,1)];

        $this->response
            ->json('POST', '/api/quizzes', $data)
            ->assertStatus(201)
            ->assertJson([
                'created' => true,
                'id' => true
            ]);
    }


    public function testIndex()
    {
        $this->response
            ->json('GET', '/api/quizzes')
            ->assertStatus(200)
            ->assertJsonStructure([
                'data' =>[['id', 'title', 'public']],
            ]);
    }


//    public function testShow()
//    {
//
//    }
//
//    public function testEdit()
//    {
//
//    }
//
//    public function testDelete()
//    {
//
//    }

}
